### PR TITLE
English language correction. 

### PR DESCRIPTION
**Pull request by MFernflower**
Hello there, I have rewritten the English lang file to make it more professional and correct. I do not mean to be noxious, I just want to fix this. This mod seems cool and I may work on making a bridge between this and MineChem!

### CODE REVIEW

**Comment by rikka0w0** [comment]
Thanks so much!!!!
That's the only word I could say >_<

------------------ 原始邮件 ------------------
发件人: "Mandrake Naader Fernflower (IGN: TheDoctor15555)";notifications@github.com;
发送时间: 2013年11月21日(星期四) 凌晨0:04
收件人: "FrogCraft/FrogCraft"FrogCraft@noreply.github.com; 

主题: [FrogCraft] English language correction.  (#11)

Hello there, I have rewritten the English lang file to make it more professional and correct. I do not mean to be noxious, I just want to fix this. This mod seems cool and I may work on making a bridge between this and MineChem! 

You can merge this Pull Request by running
   git pull https://github.com/MFernflower/FrogCraft master 
Or view, comment on, or merge it at:

  https://github.com/FrogCraft/FrogCraft/pull/11

Commit Summary

Spelling and grammar corrections for the English lang file.

Update en_US.properties

File Changes

```
 M     assets/frogcraft/lang/en_US.properties     (18)   
```

Patch Links:

https://github.com/FrogCraft/FrogCraft/pull/11.patch

https://github.com/FrogCraft/FrogCraft/pull/11.diff

**Comment by rikka0w0** [comment]
And also, in the future, would you mind to help me check the English name for my mod?
PS: when MCP and forge 1.7.2 comes, frogcraft will become a seperate chemical industry mod, but still keep high compatibility with IC and GregTech and other scientific mod~

------------------ 原始邮件 ------------------
发件人: "Mandrake Naader Fernflower (IGN: TheDoctor15555)";notifications@github.com;
发送时间: 2013年11月21日(星期四) 凌晨0:04
收件人: "FrogCraft/FrogCraft"FrogCraft@noreply.github.com; 

主题: [FrogCraft] English language correction.  (#11)

Hello there, I have rewritten the English lang file to make it more professional and correct. I do not mean to be noxious, I just want to fix this. This mod seems cool and I may work on making a bridge between this and MineChem! 

You can merge this Pull Request by running
   git pull https://github.com/MFernflower/FrogCraft master 
Or view, comment on, or merge it at:

  https://github.com/FrogCraft/FrogCraft/pull/11

Commit Summary

Spelling and grammar corrections for the English lang file.

Update en_US.properties

File Changes

```
 M     assets/frogcraft/lang/en_US.properties     (18)   
```

Patch Links:

https://github.com/FrogCraft/FrogCraft/pull/11.patch

https://github.com/FrogCraft/FrogCraft/pull/11.diff

**Comment by MFernflower** [comment]
Is this mod going to be updated?

**Comment by rikka0w0** [comment]
Yes, I'm waiting for the stable version of MCP and forge for 1.7.2
 Once it comes out, I'll start rewriting this mod

 ------------------ 原始邮件 ------------------
  发件人: "Mandrake Naader Fernflower (IGN: TheDoctor15555)";notifications@github.com;
 发送时间: 2013年12月16日(星期一) 上午8:35
 收件人: "FrogCraft/FrogCraft"FrogCraft@noreply.github.com; 
 抄送: "特斯拉的接班人"929513338@qq.com; 
 主题: Re: [FrogCraft] English language correction. (#11)

Is this mod going to be updated?

**Comment by Vexatos** [comment]
Ok, then I'll also wait a little more. I love your mod, by the way.

**Pull request closed without merging**
